version: '3.3'
services:
   nginx:
       image: nginx:1.12
       depends_on:
           - digest
       networks:
           - reverse-proxy
       volumes:
           - source_code:/var/www/digest
       restart: always
       command: /bin/bash -c "cat /var/www/digest/docker/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
       environment:
           VIRTUAL_HOST: digest.stampany.com
           LETSENCRYPT_HOST: digest.stampany.com
           LETSENCRYPT_EMAIL: dario_swain@yahoo.com

   digest:
       image: registry.stampany.com/dario_swain/digest:latest
       depends_on:
           - mongo
       restart: always
       volumes:
           - source_code:/var/www/digest
       environment:
           MONGO_SERVER: 'mongodb://mongo:27017'
           MONGO_DB: 'digest'
           SECRET: '4b38b8b708f77d8b8c9bbb08b3bc655539af15b6'

   mongo:
       image: mongo:3.2
       restart: always
volumes:
  source_code:

networks:
  reverse-proxy:
    external:
      name: reverse-proxy
