version: '3.3'
services:
   nginx:
       image: nginx:1.12
       depends_on:
           - digest
       networks:
           - reverse-proxy
           - digest_default
       volumes:
           - source_code:/var/www/digest
       restart: always
       command: /bin/bash -c "apt-get update && apt-get install -y wget && wget -O wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh && chmod 777 wait-for-it.sh && cat /var/www/digest/docker/nginx.conf > /etc/nginx/conf.d/default.conf && ./wait-for-it.sh digest:9000 -- nginx -g 'daemon off;'"
       environment:
           VIRTUAL_HOST: digest.stampany.com
           LETSENCRYPT_HOST: digest.stampany.com
           LETSENCRYPT_EMAIL: dario_swain@yahoo.com

   digest:
       image: registry.stampany.com/dario_swain/digest:latest
       depends_on:
           - mongo
       restart: always
       networks:
           - digest_default
       volumes:
           - source_code:/var/www/digest
       environment:
           MONGO_SERVER: 'mongodb://mongo:27017'
           MONGO_DB: 'digest'
           SECRET: '4b38b8b708f77d8b8c9bbb08b3bc655539af15b6'
   mongo:
       image: mongo:3.2
       restart: always
       networks:
           - digest_default
volumes:
  source_code:

networks:
  digest_default:
  reverse-proxy:
    external:
      name: reverse-proxy
