DS\Digest\Domain\Digest\Model\Digest:
    embedMany:
        sections:
          targetDocument: DS\Digest\Domain\Digest\Model\Section
    fields:
        id:
            id: true
            type: string
            strategy: NONE
        name:
            type: string
        state:
            type: string
        createdAt:
            type: date
        updatedAt:
            type: date
